### ISSUE TITLE
Can't play station

### ISSUE THREAD

**Issue by bhinners** [agejevasv/goradion#4] opened 2024-05-31 17:25 UTC
I add this station to my stations.csv, but when I launch goradion, it never shows.  I tried tweaking the name several times, but that didn't help.  I'm forced to conclude that it won't load the URL for some reason.

Zoom 1980s,https://samcloud.spacial.com/api/listen?sid=111415&rid=194939&f=mp3,any&br=128000,any&m=sc

**Comment by agejevasv** [comment] 2024-06-02 05:35
Thank you for reporting, the bug is fixed in [latest build](https://github.com/agejevasv/goradion/releases/tag/v0.3.11).

The issue is that the URL contains comma characters, they have to be escaped. After updating to the latest release this should work (note the quotes around the URL which contains comma chars):
```csv
Zoom 1980s,"https://samcloud.spacial.com/api/listen?sid=111415&rid=194939&f=mp3,any&br=128000,any&m=sc"
```

**Closed as completed by agejevasv** 2024-06-02 05:35 UTC

**Comment by bhinners** [comment] 2024-06-02 12:25
I suspected the commas might be the problem.  I tried escaping them with a backslash preceding each one, but that didn't work, either.

Anyway, your solution should be alright.  Thanks for taking care of it.
